version: "3.8"

services:
  db:
    image: mysql:8.1
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mzhasan
      MYSQL_DATABASE: dagangin
      TZ: Asia/Jakarta
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "-uroot", "-pmzhasan", "ping"]
      interval: 5s
      retries: 10
    networks:
      - go-network
  app:
    build: .
    container_name: go_app
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - go-network

  nginx_proxy:
    image: nginx:stable
    container_name: nginx_proxy
    restart: always
    ports:
      - "9000:80"   # host port bisa 9000
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - go-network

volumes:
  db_data:

networks:
  go-network:
    driver: bridge
